title: Letters to Self
email: your-email@example.com
description: >
  Write an awesome description for your new site here.
baseurl: "/LettersToSelf"
url: "https://shaikrb.github.io"
twitter_username: jekyllrb
github_username: jekyll
theme: minima
plugins:
  - jekyll-feed
collections:
  booknotes:
    output: true
    permalink: /book-notes/:title/
